name: Test recsyslib

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip setuptools

    - name: Install wheel
      run: python -m pip install wheel

    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('test_requirements.txt') }}
          restore-keys:|
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

    - name: Install Deps
      run: |
        python -m pip install -r test_requirements.txt
        python -m pip install flake8
        python -m pip install -r requirements.txt
        python -m pip install -e .

    - name: Pep Lint
      run: flake8 recsyslib/

    - name: Test code
      run: python -m pytest --cov=recsyslib tests/ --junitxml=junit/test-results-${{ matrix.python-version }}.xml
